use_frameworks!

platform :ios, '9.0'

target 'DZCommonDataSource_Example' do
  pod 'DZCommonDataSource', :path => '../'

  target 'DZCommonDataSource_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
